inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false
